### ISSUE TITLE
`data` field support

### ISSUE THREAD

**Issue by yrachek** [Ceratech/fcm-scala#2]
Hey there, what about an idea to extend FcmSender to be able to send data field which represents key/value pair in fcm protocol ?

**Comment by DriesSchulten** [comment]
There is already a `data` field in the `FcmNotification` that can be used for this purpose I believe (as per [FCM docs](https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages))

Does that help?
